In [4]:
import numpy as np

In [14]:
r1 = np.load('200_circ_set_result_qubit2_1.npy',allow_pickle=True)
r2 = np.load('200_circ_set_result_qubit2_2.npy',allow_pickle=True)

In [15]:
r=np.array(r1.tolist()+r2.tolist(),object)

In [ ]:
np.sh

In [13]:
np.save('200_circ_set_result_qubit2.npy',r)

In [18]:
r1[0]

array([<qibo.models.circuit.Circuit object at 0x7fd05d113910>,
       array([[ 1.00000000e+00+0.00000000e+00j,  0.00000000e+00-1.17756934e-16j],
              [ 0.00000000e+00+1.11022302e-16j, -3.92523115e-17+0.00000000e+00j]]),
       array([[0.825+0.j   , 0.166-0.105j],
              [0.166+0.105j, 0.175+0.j   ]]),
       array([[0.93170732+0.j        , 0.04390244+0.10487805j],
              [0.04390244-0.10487805j, 0.06829268+0.j        ]]),
       array([[ 1.35853659, -1.0804878 ],
              [-0.35853659,  2.0804878 ]])], dtype=object)

In [5]:
r = np.load('200_circ_set_result.npy',allow_pickle=True)

In [8]:
from scipy.linalg import inv

In [10]:
inv(r[0][4])

array([[0.853, 0.443],
       [0.147, 0.557]])

In [46]:
len(r) 

200

In [1]:
import qibo

In [2]:
qibo.__version__

'0.2.5'

In [3]:
r[0]

NameError: name 'r' is not defined